# -*- coding: utf-8 -*-
"""Multiple_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-4lic-i3eJB7kJJfVTzF5O67NgNcJ5d-

# **Import all the necessary Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""# **Load the csv data using the pandas**"""

df = pd.read_csv('50_Startups.csv')
df

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

"""# **Data Preprocessing**"""

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder' , OneHotEncoder(),[3])],remainder='passthrough')
x = np.array(ct.fit_transform(x))

"""# **Train Test Split**"""

from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2, random_state=0)

"""# **Applying the multiple linear regression to the training set**"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train ,y_train)

"""# **Predicting the Test set result**"""

y_pred = regressor.predict(x_test)

np.set_printoptions(precision = 2)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))