# -*- coding: utf-8 -*-
"""Simple_Linear_Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1TpcVoncCdZI-qzNAYkARoXVpqOkGBeuS

# **Import all the necessary Libraries**
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

"""## **Loading the csv data into the variable using the pandas**"""

df = pd.read_csv('Salary_Data.csv')
df

"""#**Identifying the independent and the dependent variable**"""

x = df.iloc[:,:-1].values
y = df.iloc[:,-1].values

"""# **Split into train and test set**"""

from  sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split(x,y, test_size=0.2 , random_state=0)

"""# **Apply Linear Regression**"""

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train , y_train)

y_pred = regressor.predict(x_test)

"""# **Visualising the Training set**"""

plt.scatter(x_train,y_train, color= 'red')
plt.plot(x_train , regressor.predict(x_train), color = 'blue')
plt.title('Salary vs Experience (Training set)')
plt.xlabel('Experience in yrs')
plt.ylabel('Salary')
plt.show()

"""# **Visualising the Test set**"""

plt.scatter(x_test , y_test, color = 'red')
plt.plot(x_test , regressor.predict(x_test), color= 'blue')
plt.title('Salary vs Experience (test set)')
plt.xlabel('Experience in years')
plt.ylabel('Salary')
plt.show()